### ISSUE TITLE
About data usage memory

### ISSUE THREAD

**Issue by ZHUXUHAN** [fawazsammani/knowing-when-to-look-adaptive-attention#1]
hi，How much memory does your experiment store in addition to the dataset?

**Comment by fawazsammani** [comment]
Hi @ZHUXUHAN 
Im using a GTX1060 with 6GB RAM. That's why i couldnt finetune further CNN layers (only finetuned the last layer) since i dont have enough memory for the parameters.

**Comment by gorgeousyouth** [comment]
> Hi @ZHUXUHAN
> Im using a GTX1060 with 6GB RAM. That's why i couldnt finetune further CNN layers (only finetuned the last layer) since i dont have enough memory for the parameters.

excuse me, is this project completely implement the result of the paper?
best,

**Comment by fawazsammani** [comment]
Hi @gorgeousyouth 
Yes. I only trained it for 9 epochs. You'd probably want to train it more to get better results. Unfortunately i deleted the trained model by accident, so i cant upload it here.
