### ISSUE TITLE
About Beam Search

### ISSUE THREAD

**Issue by czhxiaohuihui** [fawazsammani/knowing-when-to-look-adaptive-attention#2]
When I run visualize.ipynb, I find "caption_image_beam_search" generates worse results than just use the "predict_output" and have more repeat result!
Is their some bug in the beam search implementation?

**Comment by fawazsammani** [comment]
Hi @czhxiaohuihui ,
How many epochs did you train it for? At the first couple of epochs, it will generate words that never reach to <end>, as discussed in this issue [here](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning/issues/18). The beam search implementation is correct 100%, and it is acquired from the reference I posted. It also works well with many images I tested on. Maybe it could be of bad training. How much did you get for the bleu result?

**Comment by czhxiaohuihui** [comment]
This is my best log: "BEST_checkpoint_8_0.23796299837520654.pth.tar"
And I set  "epochs=50" ,but I stopped it by myself after some epochs.
Thanks you very much, I will check my training!

**Comment by fawazsammani** [comment]
@czhxiaohuihui If you train it for a couple more epochs, and fine-tune the encoder, you should get the bleu-4 results reported by the paper (0.251). However, at this time with 8 epochs only, you should already get a good result. Try with different images. It may be that the image you experimented on gives a unique result.
