### ISSUE TITLE
is batch_size_t work ?

### ISSUE THREAD

**Issue by zmskye** [fawazsammani/knowing-when-to-look-adaptive-attention#4]
Hi, there is a 'batch_size_t'，which will filter the samples that have short length, but why do this, I dont think this will work, maybe this will lead the model adopt very few samples?
`batch_size_t = sum([l > timestep for l in decode_lengths]) \n
current_input = inputs[:batch_size_t, timestep, :]`

Please help me, thanks.

**Comment by fawazsammani** [comment]
Hi. This is just like coding `pack_padded_sequence` from scratch. However, since we are using `nn.LSTMCell ` we cannot use it because it is only available for `nn.LSTM`. At each timestep, we are finding the batch size depending on the decoded length.

**Comment by zmskye** [comment]
Hi, Thanks for your reply, could you please tell me your highest bleu-4 score on the validation dataset?

**Comment by fawazsammani** [comment]
On Flickr30k, it was around 0.260. I'll probably re-train the model (because I accidently deleted it :( 
and upload it once I have time.

**Comment by zmskye** [comment]
LOL，good luck bro !
