### ISSUE TITLE
beta_t is always 1

### ISSUE THREAD

**Issue by shadowclouds** [fawazsammani/knowing-when-to-look-adaptive-attention#5]
I try to test the pretrained model imitate https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioningand find that beta is always 1. Did you test the beta of the trained model? Is it right?

**Comment by fawazsammani** [comment]
Hi. I haven't visualized the beta_t. I will figure out what's the problem ang get back to you. Thanks for letting me know!

**Comment by fawazsammani** [comment]
Hi @shadowclouds . The problem is fixed already. You can see the image attached. 
![Capture`](https://user-images.githubusercontent.com/30661597/58306065-d9d84180-7e2c-11e9-84bd-e7aec3e434a7.PNG)
I will update the code + re-train the model and upload it here.
Regards

**Comment by YifanYu5124** [comment]
Hi @fawazsammani May we ask what caused the incorrect beta, and what changes are needed to fix it? My team has been working on image captioning using the previous version of the code and added some new features. We saw there were a lot of new commits within the past week, and therefore were not sure which one was for fixing the beta issue mentioned here. Would really appreciate it if you could point a direction for us. Thank you!

**Comment by fawazsammani** [comment]
Hi @YifanYu5124 . Sure thing. Please accept my apology for not informing about the updates. There was a small mistake in extracting the features from the Encoder CNN. I only added this line: 
`enc_image = encoded_image.permute(0, 2, 3, 1)  #  (batch_size,7,7,2048)` before `enc_image = enc_image.view(batch_size,num_pixels,features)`. I also changed the AdaptiveLSTMCell to using the PyTorch nn.LSTMCell (but this won't affect, you can just leave it as it was in the previous version). 
Let me know if you need any more information. Regards

**Comment by YifanYu5124** [comment]
Hi @fawazsammani Not a problem at all! Actually thank you so much for this awesome implementation of adaptive attention. It really helps us a lot.  Got it! We will add that line. Thank you for getting back to us so quickly!
