### ISSUE TITLE
the dimension of enc_image is right?

### ISSUE THREAD

**Issue by Doragd** [fawazsammani/knowing-when-to-look-adaptive-attention#6]
In models.py:  line 45 and line 53
```
encoded_image = self.resnet(images)         # (batch_size,2048,7,7)
enc_image = encoded_image.view(batch_size,num_pixels,features) # (batch_size, 49,2048)
```
 I think you should permute the axises first, and then apply the “view” function. 
i.e.
```
encoded_image = self.resnet(images)         # (batch_size,2048,7,7)
enc_image = encoded_image.permute(0, 2, 3, 1)  #  (batch_size,7,7,2048)
enc_image = enc_image.view(batch_size,num_pixels,features) # (batch_size, 49,2048)
```
Do you think so?

**Comment by fawazsammani** [comment]
Hi,
Actually, you are right. I didn't notice that small mistake. What's happening is the features are acting as pixels. I will correct it and re-train the whole model by tonight and inform you about the results. Thanks for pointing this out. I will reference your issue in the readme file.

**Comment by Doragd** [comment]
I also thank you for your open source code. It really helps me a lot.
