### ISSUE TITLE
when run preprocess.py I got this  error？

### ISSUE THREAD

**Issue by neverstoplearn** [fawazsammani/knowing-when-to-look-adaptive-attention#7]
Traceback (most recent call last):
  File "preprocess.py", line 114, in <module>
    img = img.transpose(2, 0, 1)                        # make the channels (index 2) first,as expected by PyTorch
ValueError: axes don't match array

**Comment by TodayUp** [comment]
> Traceback (most recent call last):
> File "preprocess.py", line 114, in 
> img = img.transpose(2, 0, 1) # make the channels (index 2) first,as expected by PyTorch
> ValueError: axes don't match array

Hello!Have you solved it?I got it too.

**Comment by fawazsammani** [comment]
@neverstoplearn @TodayUp 
Sorry for the late reply. It seems that you encountered a grayscale image rather than an RGB image in the dataset you are using. 

Please add the following directly after `img = imread(impaths[i])`:

```
if len(img.shape) == 2:
     img = img[:, :, np.newaxis]
     img = np.concatenate([img, img, img], axis=2)
```

**Comment by TodayUp** [comment]
> @neverstoplearn @TodayUp
> Sorry for the late reply. It seems that you encountered a grayscale image rather than an RGB image in the dataset you are using.
> 
> Please add the following directly after `img = imread(impaths[i])`:
> 
> ```
> if len(img.shape) == 2:
>      img = img[:, :, np.newaxis]
>      img = np.concatenate([img, img, img], axis=2)
> ```
> 
> This should solve the problem.

Yeah，it works. Thanks for u!
